#' Title Calculate Cluster information
#'
#' @param x scRNA
#' @param res resolution that you want to cluster
#' @param npcs the param of runPCA
#' @param dims which numbers of npcs you want to use
#'
#' @return ScRNA that be cluster
#' @export
#' @importFrom ggraph guide_edge_colourbar
#' @importFrom grDevices dev.off png
#' @import clustree
#'
Cluster_ScRNA <- function(x = scRNA, res = c(seq(.1, 1.6, .2)), npcs = 30, dims = 1:30) {
  if (missing(x)) {
    message("Missing x, Use default scRNA")
    if (!exists("scRNA")) {
      stop("didn't find scRNA, Please check scRNA is exists or not, scRNA is generated by Normalize_IntegrateSclist, it is a legal integrated Seurat object. ")
    } else {
      checkmate::assert_class(scRNA, "Seurat")
    }
  } else {
    checkmate::assert_class(scRNA, "Seurat")
  }
  if (missing(res)) {
    message("Missing Param res, Use default param res=c(0.1,0.3,0.5,0.7,0.9,1.1,1.3,1.5)")
  } else {
    checkmate::assertDouble(res)
  }
  if (missing(npcs)) {
    message("Missing Param npcs, Use default param npcs=30")
  } else {
    checkmate::assertCount(npcs)
  }
  if (missing(dims)) {
    message("Missing Param dims, Use default param dims=1:30")
  } else {
    checkmate::assert_integer(dims)
  }
  message("\n Starting scale...")
  x <- ScaleData(x)
  message("\n Starting RunPCA, Use npcs = ", npcs)
  x <- RunPCA(x, npcs = npcs)
  message("\n Starting RunUMAP, Use dims = ", dims)
  x <- RunUMAP(x, reduction = "pca", dims = dims)
  Check_figdir()
  message("\n Visualizing PCA, Save fig as VizDimLoadings_1-3.jpg in fig/")
  p1 <- VizDimLoadings(x, dims = 1:3, reduction = "pca", ncol = 3)
  ggsave("fig/VizDimLoadings_1-3.jpg", p1, width = 18, height = 8, limitsize = F)
  p2 <- DimPlot(x, reduction = "pca", group.by = "sample")
  p3 <- DimPlot(x, reduction = "pca", group.by = "patient")
  message("\n Visualizing PCA by group, Save as DimPlot_sample_pca.jpg; DimPlot_patient_pca.jpg in fig/")
  ggsave("fig/DimPlot_sample_pca.jpg", p2, width = 8, height = 8, limitsize = F)
  ggsave("fig/DimPlot_patient_pca.jpg", p3, width = 8, height = 8, limitsize = F)
  # DimHeatmap(x, dims = 1, cells = 500, balanced = TRUE)
  # Select pcs dim , see ElbowPlot
  message("\n check top 30 PCA weight, save as ElbowPlot_pca.jpg in fig/")
  p4 <- ElbowPlot(x, ndims = 30)
  png("fig/ElbowPlot_pca.png")
  print(p4)
  dev.off()
  # ggsave("fig/ElbowPlot_pca.jpg",p4,width = 12,height = 8,limitsize = F)

  message("\n Starting cluster...")
  x <- FindNeighbors(x, reduction = "pca", dims = dims)
  x <- FindClusters(
    object = x,
    resolution = res
  )
  message("\n \n \nUse clustree Visualize every node in reduction, Result save as Clustree_res.jpg in fig/")
  p5 <- clustree::clustree(x@meta.data, prefix = "integrated_snn_res.")
  ggsave("fig/Clustree_res.jpg", p5, width = 18, height = 8, limitsize = F)

  message("\n \nSave ccRNA-Cluster object as ccRNA_Cluster.Rdata (Rdata)")
  save(x, file = "ccRNA_Cluster.Rdata")
  message("\n \n \n       --------------Cluster ScRNA Successfully------------")

  return(x)
}
