#' Title Plot_scatter in integrated Seurat object, find corresponding between virus and cells
#'
#' @param x scRNA that is integrated Seurat object
#'
#' @return Plot object
#' @export
#' @importFrom ggplot2 ggsave
#' @import patchwork
#'
Plot_Scatter<-function(x=scRNA){
  # check param x
  if (missing(x)) {
    message('Missing x, Use default scRNA')
    if (!exists("scRNA")){
      stop("didn't Find scRNA, Please check scRNA if it is exists. scRNA should be generated by Normalize_IntegrateSclist, it is a legal Seurat object and is normalized")
    }
  }
  Check_figdir()
  message("\n \nStarting VlnPlot...")
  # plotfigure
  p1<-VlnPlot(scRNA, features = c("nFeature_RNA", "nCount_RNA", "virus"), ncol = 3,group.by = "patient",split.by = "sample" ,pt.size = 0.0001)
  message("save VlnPlot as n_feature_counts_virus_Vlnplot.jpg, save in fig/ directory...")
  ggplot2::ggsave(filename = "fig/n_feature_counts_virus_Vlnplot.jpg",p1,width = 18,height = 8,limitsize = F)
  message("\n  \nStart plot FeatureScatter...")

  p2<-FeatureScatter(scRNA,feature1 = "nFeature_RNA",feature2 = "nCount_RNA")+NoLegend()
  p3<-FeatureScatter(scRNA,feature1 = "nFeature_RNA",feature2 = "virus")+NoLegend()
  p4<-FeatureScatter(scRNA,feature1 = "nCount_RNA",feature2 = "virus")+NoLegend()
  p5<-p2+p3+p4+plot_layout(guides = 'collect')+plot_annotation(title = "nfeature_counts_virus_scatterplot")
  message("Save FeatureScatter as n_feature_counts_virus_scatterplot.jpg, save in fig/ folder...")
  ggplot2::ggsave(filename="fig/n_feature_counts_virus_scatterplot.jpg",p5,width = 18,height = 8,limitsize = F)
  message("\n \n Plot completely!!!!!")
  return(list(VlnPlot=p1,FeatureScatter=p5))
}
