#' Title Plot Cluster by orig.ident/sample/patient in your specific resolution
#'
#' @param x input ccRNA
#' @param res resolution you want to plot
#'
#' @return Cluster Plot
#' @export
#'
Plot_Cluster<-function(x=ccRNA,res=0.5){
  if (missing(x)) {
    message('\nMissing x, Use default ccRNA')
    if (!exists("ccRNA") || !inherits(ccRNA,"Seurat")){
      stop("Didn't find ccRNA, Please check if ccRNA exists or not. ccRNA is generated by Cluster_ScRNA or Recluster_CcRNA, it is a legal Seurat object and has been Clusterred.")
    }
  }
  if (missing(res)) {
    message('\nMissing res, Use default param 0.5')
  }else{
    checkmate::assertDouble(res)
  }
  if (!is.element(paste0("integrated_snn_res.",res),names(x@meta.data))){
    cat("\n \nx has resolution :",names(x@meta.data)[grep("integrated_snn_res.",names(x@meta.data))],"\n")
    stop("\nThis RES is not found in input x, re-check whether the ccrna exists. CCRNA-RES should be generated by Cluster_Seurat or Recluster_CcRNA, characterized like integrated_snn_res.",res)
  }

  sample_num = length(unique(x$orig.ident))
  message("\n \nCalculate plot ncol by orig.ident size: ",sample_num)
  message("\n \nStart plot, Use method UMAP, group by patient, sample, orig.ident, and Save as Cluster**.jpg Format in fig/ folder ")
  p7<-DimPlot(x, reduction = 'umap', group.by = paste0("integrated_snn_res.",res),label = TRUE,pt.size = 0.1)
  p8<-DimPlot(x, reduction = 'umap', group.by = paste0("integrated_snn_res.",res),split.by = "patient",label = TRUE,pt.size = 0.1)
  p9<-DimPlot(x, reduction = 'umap', group.by = paste0("integrated_snn_res.",res),split.by = "sample",label = TRUE,pt.size = 0.1,ncol = ceiling(sample_num/2))
  p10<-DimPlot(x, reduction = 'umap', group.by = paste0("integrated_snn_res.",res),split.by = "orig.ident",label = TRUE,pt.size = 0.1,ncol = floor(sqrt(sample_num))+1)
  Check_figdir()
  ggsave(paste0("fig/Cluster_res",res,".jpg"),p7,width = 8,height = 8,limitsize = F)
  message("\nComplete save  ",paste0("fig/Cluster_res",res,".jpg")," ...")
  ggsave(paste0("fig/Cluster_patient_res",res,".jpg"),p8,width = 12,height = 8,limitsize = F)
  message("\nComplete save  ",paste0("fig/Cluster_patient_res",res,".jpg")," ...")
  ggsave(paste0("fig/Cluster_sample_res",res,".jpg"),p9,width = 18,height = 8,limitsize = F)
  message("\nComplete save  ",paste0("fig/Cluster_sample_res",res,".jpg")," ...")
  ggsave(paste0("fig/Cluster_orig.ident_res",res,".jpg"),p10,width = 18,height = 12,limitsize = F)
  message("\nComplete save  ",paste0("fig/Cluster_orig.ident_res",res,".jpg")," ...")

  message("\n \n \n \n -----------Complete save Plot_Cluster !!-----------")
  return(list(cluster=p7,byorig=p10,bypatient=p8,bysample=p9))
}
