#' Title Input Virus Counts to Seurat-list
#'
#' @param x vclist
#' @param meta metadata
#' @param sct sclist
#' @return svclist
#' @export
#' @description  svclist<-ViralinSeurat() # This step is put Virus counts in Sclist, generat a Svclist.
#' @importFrom utils read.csv setTxtProgressBar str txtProgressBar

VirusinSclist <- function(x = vclist,
                          sct = sclist,
                          meta = metadata) {
  if (missing(x)) {
    message("Missing X, check the input, replacing the default vclist")
    if (!exists("vclist")) {
      stop("Missing vclist,Need to give imported virus Count data (Vclist)")
    }
  }
  if (!inherits(sct, "sclist")) {
    stop("Check if the input SCT is compliant, should be generated by Input_Sclist SCLIST format")
  }
  if (missing(meta)) {
    meta <- Check_meta()
  }
  if (!all(is.element(names(x), meta$RAW_data))) {
    stop("the elements in the vclist are not corresponding to the Raw_Data in Meta, please check the input")
  }
  if (missing(sct)) {
    message("Use default sclist")
    if (!exists("sclist")) {
      stop("Missing sclist, Please check input transposon sclist data")
    }
  }

  # Determine the correspondence between each element in the VCList to the Raw_Data in Metadata
  idm <- match(names(x), meta$RAW_data)
  cat("(", names(x), ")  correspond with (", idm, ") in RAW_data.")
  pd <- txtProgressBar(style = 3)
  for (i in 1:length(x)) {
    cat(
      "\n writing in vclist No.",
      i,
      "element ...........",
      i,
      "/",
      length(x),
      "\n"
    )
    setTxtProgressBar(pd, i / length(x))
    # filter intersection
    idx <- is.element(names(x[[i]]), colnames(sct[[idm[i]]]))
    # assign(paste0(virus[i],'in'),
    # select intersection
    a <- vclist[[i]][idx]
    # match index
    ids <- match(names(a), colnames(sct[[idm[i]]]))
    # write Virus counts in sclist by index
    sct[[idm[i]]]$virus[ids] <- a
    message("\n sclist[[", idm[i], "]] has been covered by Vclist[[", i, "]]")
    # Cover hasvirus feature by Virus count feature
    b <- as.logical(sct[[idm[i]]]$virus)
    sct[[idm[i]]]$hasvirus <- b
  }
  close(pd)
  message("Complete all viral readings ~~~")
  return(sct)
  # message("save new virus counts sclist as svclist.Rdata")
  # save(sct,file="svclist.Rdata")
}
